# Generated by Django 4.2 on 2023-05-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_alter_droprates_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="droprates",
            name="silver_per_hit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="droprates",
            name="xp_per_hit",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
