# Generated by Django 4.2.2 on 2023-12-12 03:29

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_val_per_hit"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="locationitem",
            name="snapshot_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="locationitem",
            name="snapshot_update",
        ),
        migrations.AddField(
            model_name="droprates",
            name="frozen",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="locationitem",
            name="frozen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="locationitemevent",
            name="frozen",
            field=models.BooleanField(default=False),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="locationitem",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "locations_locationitemevent" ("frozen", "id", "item_id", "location_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sometimes") VALUES (NEW."frozen", NEW."id", NEW."item_id", NEW."location_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."sometimes"); RETURN NULL;',
                    hash="a346ca54fc606914a1edd52bb508313598fd8f87",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_36876",
                    table="locations_locationitem",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="locationitem",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "locations_locationitemevent" ("frozen", "id", "item_id", "location_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sometimes") VALUES (NEW."frozen", NEW."id", NEW."item_id", NEW."location_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."sometimes"); RETURN NULL;',
                    hash="0990c0cd3f4e2f3ba1bdbb92f326ac980be533cf",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_235f1",
                    table="locations_locationitem",
                    when="AFTER",
                ),
            ),
        ),
    ]
