# Generated by Django 4.2.2 on 2023-12-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_frozen_fishing"),
    ]

    operations = [
        migrations.AddField(
            model_name="droprates",
            name="frozen_only",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
