# Generated by Django 4.2.17 on 2026-09-08 07:00

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0026_temple'),
        ('locations', '0007_frozen_only'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='location',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='location',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='locationitem',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='locationitem',
            name='snapshot_update',
        ),
        migrations.AddField(
            model_name='location',
            name='mining_charm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charm_locations', to='items.item'),
        ),
        migrations.AddField(
            model_name='location',
            name='mining_lantern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lantern_locations', to='items.item'),
        ),
        migrations.AddField(
            model_name='location',
            name='mining_pickaxe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickaxe_locations', to='items.item'),
        ),
        migrations.AddField(
            model_name='locationevent',
            name='mining_charm',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='items.item'),
        ),
        migrations.AddField(
            model_name='locationevent',
            name='mining_lantern',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='items.item'),
        ),
        migrations.AddField(
            model_name='locationevent',
            name='mining_pickaxe',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='items.item'),
        ),
        migrations.AddField(
            model_name='locationitem',
            name='mining_deposit_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationitem',
            name='mining_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationitemevent',
            name='mining_deposit_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationitemevent',
            name='mining_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('explore', 'Exploring'), ('fishing', 'Fishing'), ('mining', 'Mining')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='locationevent',
            name='type',
            field=models.CharField(choices=[('explore', 'Exploring'), ('fishing', 'Fishing'), ('mining', 'Mining')], max_length=32),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='location',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "locations_locationevent" ("base_drop_rate", "created_at", "game_id", "id", "image", "mining_charm_id", "mining_lantern_id", "mining_pickaxe_id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "type") VALUES (NEW."base_drop_rate", NEW."created_at", NEW."game_id", NEW."id", NEW."image", NEW."mining_charm_id", NEW."mining_lantern_id", NEW."mining_pickaxe_id", NEW."name", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."type"); RETURN NULL;', hash='fd0ebad4a899c452fce8706ca1e94592f59531fa', operation='INSERT', pgid='pgtrigger_snapshot_insert_16203', table='locations_location', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='location',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."game_id" IS DISTINCT FROM (NEW."game_id") OR OLD."type" IS DISTINCT FROM (NEW."type") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."image" IS DISTINCT FROM (NEW."image") OR OLD."base_drop_rate" IS DISTINCT FROM (NEW."base_drop_rate") OR OLD."mining_pickaxe_id" IS DISTINCT FROM (NEW."mining_pickaxe_id") OR OLD."mining_charm_id" IS DISTINCT FROM (NEW."mining_charm_id") OR OLD."mining_lantern_id" IS DISTINCT FROM (NEW."mining_lantern_id") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func='INSERT INTO "locations_locationevent" ("base_drop_rate", "created_at", "game_id", "id", "image", "mining_charm_id", "mining_lantern_id", "mining_pickaxe_id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "type") VALUES (NEW."base_drop_rate", NEW."created_at", NEW."game_id", NEW."id", NEW."image", NEW."mining_charm_id", NEW."mining_lantern_id", NEW."mining_pickaxe_id", NEW."name", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."type"); RETURN NULL;', hash='fef4be5a138231ad5d777dc834d387c2a2bb915b', operation='UPDATE', pgid='pgtrigger_snapshot_update_d2a04', table='locations_location', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='locationitem',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "locations_locationitemevent" ("frozen", "id", "item_id", "location_id", "mining_deposit_quantity", "mining_level", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sometimes") VALUES (NEW."frozen", NEW."id", NEW."item_id", NEW."location_id", NEW."mining_deposit_quantity", NEW."mining_level", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."sometimes"); RETURN NULL;', hash='e7dba5bb5fbc67d40ca859505a206450c6bfeaf1', operation='INSERT', pgid='pgtrigger_snapshot_insert_36876', table='locations_locationitem', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='locationitem',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "locations_locationitemevent" ("frozen", "id", "item_id", "location_id", "mining_deposit_quantity", "mining_level", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sometimes") VALUES (NEW."frozen", NEW."id", NEW."item_id", NEW."location_id", NEW."mining_deposit_quantity", NEW."mining_level", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."sometimes"); RETURN NULL;', hash='727b543f27d0b3906a315bc458e163fa11fd644c', operation='UPDATE', pgid='pgtrigger_snapshot_update_235f1', table='locations_locationitem', when='AFTER')),
        ),
    ]
