# Generated by Django 4.2.17 on 2026-09-08 11:21

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_remove_location_snapshot_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='locationitem',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='locationitem',
            name='snapshot_update',
        ),
        migrations.RenameField(
            model_name='locationitem',
            old_name='mining_level',
            new_name='mining_floor',
        ),
        migrations.RenameField(
            model_name='locationitemevent',
            old_name='mining_level',
            new_name='mining_floor',
        ),
        migrations.AddField(
            model_name='droprates',
            name='mining_floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='locationitem',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "locations_locationitemevent" ("frozen", "id", "item_id", "location_id", "mining_deposit_quantity", "mining_floor", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sometimes") VALUES (NEW."frozen", NEW."id", NEW."item_id", NEW."location_id", NEW."mining_deposit_quantity", NEW."mining_floor", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."sometimes"); RETURN NULL;', hash='c6985817274f97eb79138767008d195562dd813d', operation='INSERT', pgid='pgtrigger_snapshot_insert_36876', table='locations_locationitem', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='locationitem',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "locations_locationitemevent" ("frozen", "id", "item_id", "location_id", "mining_deposit_quantity", "mining_floor", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sometimes") VALUES (NEW."frozen", NEW."id", NEW."item_id", NEW."location_id", NEW."mining_deposit_quantity", NEW."mining_floor", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."sometimes"); RETURN NULL;', hash='1165a0738dc3b75218217ef32ab0b0cc9de283fe', operation='UPDATE', pgid='pgtrigger_snapshot_update_235f1', table='locations_locationitem', when='AFTER')),
        ),
    ]
