# Generated by Django 4.2 on 2023-05-25 01:42

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("items", "0013_cooking_level"),
        ("pghistory", "0005_events_middlewareevents"),
    ]

    operations = [
        migrations.CreateModel(
            name="BorgenItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("price", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borgen_items",
                        to="items.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BorgenItemEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("date", models.DateField()),
                ("price", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="items.item",
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="event",
                        to="borgen.borgenitem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="borgenitem",
            constraint=models.UniqueConstraint(
                fields=("date", "item"), name="date_item"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="borgenitem",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "borgen_borgenitemevent" ("created_at", "date", "id", "item_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "price") VALUES (NEW."created_at", NEW."date", NEW."id", NEW."item_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."price"); RETURN NULL;',
                    hash="9de171c57897ce77897df6341c988e766f7b6a0b",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_97c82",
                    table="borgen_borgenitem",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="borgenitem",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."date" IS DISTINCT FROM (NEW."date") OR OLD."item_id" IS DISTINCT FROM (NEW."item_id") OR OLD."price" IS DISTINCT FROM (NEW."price") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at"))',
                    func='INSERT INTO "borgen_borgenitemevent" ("created_at", "date", "id", "item_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "price") VALUES (NEW."created_at", NEW."date", NEW."id", NEW."item_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."price"); RETURN NULL;',
                    hash="cf494028f0c997d8ce23edfc44abd1026ca259ab",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_0b284",
                    table="borgen_borgenitem",
                    when="AFTER",
                ),
            ),
        ),
    ]
