# Generated by Django 4.2 on 2023-05-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borgen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borgenitem",
            options={"ordering": ["-date", "item"]},
        ),
    ]
