# Generated by Django 4.2 on 2023-05-02 05:15

from django.db import migrations, models
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="user",
            name="snapshot_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="user",
            name="snapshot_update",
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userevent",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userevent",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "users_userevent" ("created_at", "firebase_uid", "id", "modified_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "username") VALUES (NEW."created_at", NEW."firebase_uid", NEW."id", NEW."modified_at", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."role", NEW."username"); RETURN NULL;',
                    hash="384bd0da0dbac85ce24d1f8376ebbf86cfb1c854",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_a79f7",
                    table="users_user",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "users_userevent" ("created_at", "firebase_uid", "id", "modified_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "username") VALUES (NEW."created_at", NEW."firebase_uid", NEW."id", NEW."modified_at", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."role", NEW."username"); RETURN NULL;',
                    hash="18b44071b447ac153c8deb0b3e19dd5cdf70c184",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_e726b",
                    table="users_user",
                    when="AFTER",
                ),
            ),
        ),
    ]
