# Generated by Django 4.1.5 on 2023-01-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("image", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("xp", models.IntegerField()),
                ("can_buy", models.BooleanField()),
                ("can_sell", models.BooleanField()),
                ("can_mail", models.BooleanField()),
                ("can_craft", models.BooleanField()),
                ("can_master", models.BooleanField()),
                ("description", models.TextField()),
                ("sell_price", models.IntegerField()),
                ("crafting_level", models.IntegerField()),
                ("base_yield_minutes", models.IntegerField()),
                ("min_mailable_level", models.IntegerField()),
            ],
        ),
    ]
