# Generated by Django 4.2 on 2023-05-20 04:21

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pghistory", "0005_events_middlewareevents"),
        ("items", "0006_remove_item_snapshot_insert_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WishingWellItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chance", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "input_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishing_well_input_items",
                        to="items.item",
                    ),
                ),
                (
                    "output_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishing_well_output_items",
                        to="items.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WishingWellItemEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("chance", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "input_item",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="items.item",
                    ),
                ),
                (
                    "output_item",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="items.item",
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="event",
                        to="items.wishingwellitem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="wishingwellitem",
            constraint=models.UniqueConstraint(
                fields=("input_item", "output_item"), name="input_output"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="wishingwellitem",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "items_wishingwellitemevent" ("chance", "created_at", "id", "input_item_id", "output_item_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."chance", NEW."created_at", NEW."id", NEW."input_item_id", NEW."output_item_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id"); RETURN NULL;',
                    hash="2cffeff8b66b6d5e95222dc5c33d317298b63cbc",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_1c8fa",
                    table="items_wishingwellitem",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="wishingwellitem",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."input_item_id" IS DISTINCT FROM (NEW."input_item_id") OR OLD."chance" IS DISTINCT FROM (NEW."chance") OR OLD."output_item_id" IS DISTINCT FROM (NEW."output_item_id") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at"))',
                    func='INSERT INTO "items_wishingwellitemevent" ("chance", "created_at", "id", "input_item_id", "output_item_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."chance", NEW."created_at", NEW."id", NEW."input_item_id", NEW."output_item_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id"); RETURN NULL;',
                    hash="38b37f7f676b36cdddadbc25332dec49a161d95d",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_3ed55",
                    table="items_wishingwellitem",
                    when="AFTER",
                ),
            ),
        ),
    ]
