# Generated by Django 4.2 on 2023-06-04 05:01

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0016_manual_fishing_only"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="skilllevelreward",
            name="snapshot_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="skilllevelreward",
            name="snapshot_update",
        ),
        migrations.RemoveConstraint(
            model_name="skilllevelreward",
            name="skill_level_reward_only_one_type",
        ),
        migrations.AddField(
            model_name="skilllevelreward",
            name="ak",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="skilllevelrewardevent",
            name="ak",
            field=models.IntegerField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="skilllevelreward",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "items_skilllevelrewardevent" ("ak", "gold", "id", "item_id", "item_quantity", "level", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "silver", "skill") VALUES (NEW."ak", NEW."gold", NEW."id", NEW."item_id", NEW."item_quantity", NEW."level", NEW."order", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."silver", NEW."skill"); RETURN NULL;',
                    hash="9e475789d42a27181cb24f4d2c4777b01d205879",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_0a19f",
                    table="items_skilllevelreward",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="skilllevelreward",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "items_skilllevelrewardevent" ("ak", "gold", "id", "item_id", "item_quantity", "level", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "silver", "skill") VALUES (NEW."ak", NEW."gold", NEW."id", NEW."item_id", NEW."item_quantity", NEW."level", NEW."order", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."silver", NEW."skill"); RETURN NULL;',
                    hash="4a2ded7af900bba134819deb3dab2594da941a56",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_818dc",
                    table="items_skilllevelreward",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="skilllevelreward",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("ak", None),
                        ("gold", None),
                        ("item", None),
                        ("item_quantity", None),
                        ("silver__isnull", False),
                    ),
                    models.Q(
                        ("ak", None),
                        ("gold__isnull", False),
                        ("item", None),
                        ("item_quantity", None),
                        ("silver", None),
                    ),
                    models.Q(
                        ("ak__isnull", False),
                        ("gold", None),
                        ("item", None),
                        ("item_quantity", None),
                        ("silver", None),
                    ),
                    models.Q(
                        ("ak", None),
                        ("gold", None),
                        ("item__isnull", False),
                        ("item_quantity__isnull", False),
                        ("silver", None),
                    ),
                    _connector="OR",
                ),
                name="skill_level_reward_only_one_type",
            ),
        ),
    ]
