# Generated by Django 4.2.2 on 2023-06-15 03:42

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0022_event"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="manualproduction",
            name="snapshot_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="manualproduction",
            name="snapshot_update",
        ),
        migrations.AddField(
            model_name="manualproduction",
            name="href",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="manualproductionevent",
            name="href",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="manualproduction",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "items_manualproductionevent" ("created_at", "href", "id", "image", "item_id", "line_one", "line_two", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort", "value") VALUES (NEW."created_at", NEW."href", NEW."id", NEW."image", NEW."item_id", NEW."line_one", NEW."line_two", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."sort", NEW."value"); RETURN NULL;',
                    hash="3ea1c944708850012f0a3c64f48d96d12f549635",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_a4046",
                    table="items_manualproduction",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="manualproduction",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."item_id" IS DISTINCT FROM (NEW."item_id") OR OLD."line_one" IS DISTINCT FROM (NEW."line_one") OR OLD."line_two" IS DISTINCT FROM (NEW."line_two") OR OLD."image" IS DISTINCT FROM (NEW."image") OR OLD."href" IS DISTINCT FROM (NEW."href") OR OLD."value" IS DISTINCT FROM (NEW."value") OR OLD."sort" IS DISTINCT FROM (NEW."sort") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at"))',
                    func='INSERT INTO "items_manualproductionevent" ("created_at", "href", "id", "image", "item_id", "line_one", "line_two", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort", "value") VALUES (NEW."created_at", NEW."href", NEW."id", NEW."image", NEW."item_id", NEW."line_one", NEW."line_two", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."sort", NEW."value"); RETURN NULL;',
                    hash="f53b2913d5c05c1412c98fb7c0babeda042f8cf1",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_b26d4",
                    table="items_manualproduction",
                    when="AFTER",
                ),
            ),
        ),
    ]
