# Generated by Django 4.1.5 on 2023-04-10 01:07

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pghistory", "0005_events_middlewareevents"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=255)),
                ("role", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "firebase_uid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("username", models.CharField(max_length=255)),
                ("role", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "firebase_uid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="event",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "users_userevent" ("firebase_uid", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "username") VALUES (NEW."firebase_uid", NEW."id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."role", NEW."username"); RETURN NULL;',
                    hash="926dd0692ad8429c4ab3d3ccd86fa144799a760b",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_a79f7",
                    table="users_user",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "users_userevent" ("firebase_uid", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "username") VALUES (NEW."firebase_uid", NEW."id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."role", NEW."username"); RETURN NULL;',
                    hash="0aa5d2d9b9b0a4d8f8e1b9499b90cc81ecf22491",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_e726b",
                    table="users_user",
                    when="AFTER",
                ),
            ),
        ),
    ]
