# Generated by Django 4.2 on 2023-05-03 05:46

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0003_remove_pet_snapshot_insert_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="pet",
            name="snapshot_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="pet",
            name="snapshot_update",
        ),
        migrations.RemoveField(
            model_name="petevent",
            name="modified_at",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="pet",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pets_petevent" ("cost", "created_at", "game_id", "id", "image", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "required_crafting_level", "required_exploring_level", "required_farming_level", "required_fishing_level") VALUES (NEW."cost", NEW."created_at", NEW."game_id", NEW."id", NEW."image", NEW."name", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."required_crafting_level", NEW."required_exploring_level", NEW."required_farming_level", NEW."required_fishing_level"); RETURN NULL;',
                    hash="7041ec8800e0fd6a29c3e37f1e580c07881c6fc8",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_0ddae",
                    table="pets_pet",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="pet",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."game_id" IS DISTINCT FROM (NEW."game_id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."image" IS DISTINCT FROM (NEW."image") OR OLD."cost" IS DISTINCT FROM (NEW."cost") OR OLD."required_farming_level" IS DISTINCT FROM (NEW."required_farming_level") OR OLD."required_fishing_level" IS DISTINCT FROM (NEW."required_fishing_level") OR OLD."required_crafting_level" IS DISTINCT FROM (NEW."required_crafting_level") OR OLD."required_exploring_level" IS DISTINCT FROM (NEW."required_exploring_level") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at"))',
                    func='INSERT INTO "pets_petevent" ("cost", "created_at", "game_id", "id", "image", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "required_crafting_level", "required_exploring_level", "required_farming_level", "required_fishing_level") VALUES (NEW."cost", NEW."created_at", NEW."game_id", NEW."id", NEW."image", NEW."name", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."required_crafting_level", NEW."required_exploring_level", NEW."required_farming_level", NEW."required_fishing_level"); RETURN NULL;',
                    hash="4d9d9513b52665590e16d2a94325a0e7a778be6f",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_fe0fe",
                    table="pets_pet",
                    when="AFTER",
                ),
            ),
        ),
    ]
