# Generated by Django 4.2.2 on 2023-09-24 03:43

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0004_remove_pet_snapshot_insert_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GamePet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.CharField(max_length=500)),
                ("img", models.CharField(max_length=250)),
                ("items", models.CharField(max_length=250)),
                ("items3", models.CharField(max_length=250)),
                ("items6", models.CharField(max_length=250)),
                ("price", models.BigIntegerField()),
                ("farming_level", models.IntegerField()),
                ("fishing_level", models.IntegerField()),
                ("crafting_level", models.IntegerField()),
                ("exploring_level", models.IntegerField()),
                ("cooking_level", models.IntegerField()),
                ("display_order", models.IntegerField()),
            ],
            options={
                "db_table": "pet",
                "managed": False,
            },
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="pet",
            name="snapshot_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="pet",
            name="snapshot_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="petitem",
            name="snapshot_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="petitem",
            name="snapshot_update",
        ),
        migrations.AddField(
            model_name="pet",
            name="order",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pet",
            name="required_cooking_level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="petevent",
            name="order",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="petevent",
            name="required_cooking_level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="petitem",
            name="order",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="petitemevent",
            name="order",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="pet",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pets_petevent" ("cost", "created_at", "game_id", "id", "image", "name", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "required_cooking_level", "required_crafting_level", "required_exploring_level", "required_farming_level", "required_fishing_level") VALUES (NEW."cost", NEW."created_at", NEW."game_id", NEW."id", NEW."image", NEW."name", NEW."order", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."required_cooking_level", NEW."required_crafting_level", NEW."required_exploring_level", NEW."required_farming_level", NEW."required_fishing_level"); RETURN NULL;',
                    hash="dec0542ddf94c5014970b3168f6b528e2a6bc239",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_0ddae",
                    table="pets_pet",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="pet",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."game_id" IS DISTINCT FROM (NEW."game_id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."image" IS DISTINCT FROM (NEW."image") OR OLD."cost" IS DISTINCT FROM (NEW."cost") OR OLD."order" IS DISTINCT FROM (NEW."order") OR OLD."required_farming_level" IS DISTINCT FROM (NEW."required_farming_level") OR OLD."required_fishing_level" IS DISTINCT FROM (NEW."required_fishing_level") OR OLD."required_crafting_level" IS DISTINCT FROM (NEW."required_crafting_level") OR OLD."required_exploring_level" IS DISTINCT FROM (NEW."required_exploring_level") OR OLD."required_cooking_level" IS DISTINCT FROM (NEW."required_cooking_level") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at"))',
                    func='INSERT INTO "pets_petevent" ("cost", "created_at", "game_id", "id", "image", "name", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "required_cooking_level", "required_crafting_level", "required_exploring_level", "required_farming_level", "required_fishing_level") VALUES (NEW."cost", NEW."created_at", NEW."game_id", NEW."id", NEW."image", NEW."name", NEW."order", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."required_cooking_level", NEW."required_crafting_level", NEW."required_exploring_level", NEW."required_farming_level", NEW."required_fishing_level"); RETURN NULL;',
                    hash="916760f608b3b682fa8307b99ab51888a8d42aaa",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_fe0fe",
                    table="pets_pet",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="petitem",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pets_petitemevent" ("id", "item_id", "level", "order", "pet_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."id", NEW."item_id", NEW."level", NEW."order", NEW."pet_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id"); RETURN NULL;',
                    hash="eae4cd3378d4a435dad912fd2feb94fec3f6a329",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_27dd3",
                    table="pets_petitem",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="petitem",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "pets_petitemevent" ("id", "item_id", "level", "order", "pet_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."id", NEW."item_id", NEW."level", NEW."order", NEW."pet_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id"); RETURN NULL;',
                    hash="48d406e0e2278eb37690d3393fcd6ca2a8aadc0a",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_70b5b",
                    table="pets_petitem",
                    when="AFTER",
                ),
            ),
        ),
    ]
