# Generated by Django 4.2.2 on 2023-07-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cron",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("cronspec", models.CharField(max_length=255)),
                ("previous_started_at", models.DateTimeField(blank=True, null=True)),
                ("previous_finished_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("previous_output", models.TextField(blank=True, null=True)),
                ("previous_error", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
