# Generated by Django 4.2 on 2023-05-26 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("items", "0013_cooking_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="TowerReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField()),
                ("order", models.IntegerField()),
                ("silver", models.BigIntegerField(blank=True, null=True)),
                ("gold", models.IntegerField(blank=True, null=True)),
                ("item_quantity", models.IntegerField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tower_rewards",
                        to="items.item",
                    ),
                ),
            ],
            options={
                "ordering": ["-level", "order"],
            },
        ),
        migrations.AddConstraint(
            model_name="towerreward",
            constraint=models.UniqueConstraint(
                fields=("level", "order"), name="level_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="towerreward",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("gold", None),
                        ("item", None),
                        ("item_quantity", None),
                        ("silver__isnull", False),
                    ),
                    models.Q(
                        ("gold__isnull", False),
                        ("item", None),
                        ("item_quantity", None),
                        ("silver", None),
                    ),
                    models.Q(
                        ("gold", None),
                        ("item__isnull", False),
                        ("item_quantity__isnull", False),
                        ("silver", None),
                    ),
                    _connector="OR",
                ),
                name="only_one_type",
            ),
        ),
    ]
