# Generated by Django 4.2 on 2023-05-27 02:32

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0015_constraints"),
        ("community_center", "0001_initial"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="communitycenter",
            name="snapshot_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="communitycenter",
            name="snapshot_update",
        ),
        migrations.AddField(
            model_name="communitycenter",
            name="output_gold",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="communitycenterevent",
            name="output_gold",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="communitycenter",
            name="output_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community_center_outputs",
                to="items.item",
            ),
        ),
        migrations.AlterField(
            model_name="communitycenter",
            name="output_quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="communitycenterevent",
            name="output_item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="items.item",
            ),
        ),
        migrations.AlterField(
            model_name="communitycenterevent",
            name="output_quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="communitycenter",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "community_center_communitycenterevent" ("created_at", "date", "id", "input_item_id", "input_quantity", "output_gold", "output_item_id", "output_quantity", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "progress") VALUES (NEW."created_at", NEW."date", NEW."id", NEW."input_item_id", NEW."input_quantity", NEW."output_gold", NEW."output_item_id", NEW."output_quantity", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."progress"); RETURN NULL;',
                    hash="35c9c89dfe0b01864ba3efa70c97a08ca44852c1",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_31dc5",
                    table="community_center_communitycenter",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="communitycenter",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."date" IS DISTINCT FROM (NEW."date") OR OLD."input_item_id" IS DISTINCT FROM (NEW."input_item_id") OR OLD."input_quantity" IS DISTINCT FROM (NEW."input_quantity") OR OLD."output_gold" IS DISTINCT FROM (NEW."output_gold") OR OLD."output_item_id" IS DISTINCT FROM (NEW."output_item_id") OR OLD."output_quantity" IS DISTINCT FROM (NEW."output_quantity") OR OLD."progress" IS DISTINCT FROM (NEW."progress") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at"))',
                    func='INSERT INTO "community_center_communitycenterevent" ("created_at", "date", "id", "input_item_id", "input_quantity", "output_gold", "output_item_id", "output_quantity", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "progress") VALUES (NEW."created_at", NEW."date", NEW."id", NEW."input_item_id", NEW."input_quantity", NEW."output_gold", NEW."output_item_id", NEW."output_quantity", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."progress"); RETURN NULL;',
                    hash="18573ad669dd123277df7cd076761ab628c8ee40",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_14ca2",
                    table="community_center_communitycenter",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="communitycenter",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("output_gold__isnull", False),
                        ("output_item", None),
                        ("output_quantity", None),
                    ),
                    models.Q(
                        ("output_gold", None),
                        ("output_item__isnull", False),
                        ("output_quantity__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="communitycenter_only_one_output",
            ),
        ),
    ]
