# Generated by Django 4.2.17 on 2025-10-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npcs', '0003_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npcitem',
            name='relationship',
            field=models.CharField(choices=[('can_send', 'Can Be Given '), ('loves', 'Loves'), ('likes', 'Likes'), ('hates', 'Hates')], max_length=32),
        ),
        migrations.AlterField(
            model_name='npcitemevent',
            name='relationship',
            field=models.CharField(choices=[('can_send', 'Can Be Given '), ('loves', 'Loves'), ('likes', 'Likes'), ('hates', 'Hates')], max_length=32),
        ),
    ]
