# Generated by Django 4.2.17 on 2025-10-05 02:20

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npcs', '0004_alter_npcitem_relationship_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='npc',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='npc',
            name='snapshot_update',
        ),
        migrations.AddField(
            model_name='npc',
            name='image_dec',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='image_oct',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='npcevent',
            name='image_dec',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='npcevent',
            name='image_oct',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='npc',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "npcs_npcevent" ("created_at", "id", "image", "image_dec", "image_oct", "is_available", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "short_name") VALUES (NEW."created_at", NEW."id", NEW."image", NEW."image_dec", NEW."image_oct", NEW."is_available", NEW."name", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."short_name"); RETURN NULL;', hash='779ee60ff05d5ba1e1e8bcbce6b8cb2ae63bbe41', operation='INSERT', pgid='pgtrigger_snapshot_insert_d1bdb', table='npcs_npc', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='npc',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."image" IS DISTINCT FROM (NEW."image") OR OLD."image_oct" IS DISTINCT FROM (NEW."image_oct") OR OLD."image_dec" IS DISTINCT FROM (NEW."image_dec") OR OLD."short_name" IS DISTINCT FROM (NEW."short_name") OR OLD."is_available" IS DISTINCT FROM (NEW."is_available") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func='INSERT INTO "npcs_npcevent" ("created_at", "id", "image", "image_dec", "image_oct", "is_available", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "short_name") VALUES (NEW."created_at", NEW."id", NEW."image", NEW."image_dec", NEW."image_oct", NEW."is_available", NEW."name", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."short_name"); RETURN NULL;', hash='79d080c0a2f3962d662e0f3a26632bccf9a2f7e8', operation='UPDATE', pgid='pgtrigger_snapshot_update_9156b', table='npcs_npc', when='AFTER')),
        ),
    ]
