# Generated by Django 4.2.17 on 2026-09-08 02:48

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npcs', '0005_remove_npc_snapshot_insert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPCSpecialItem',
            fields=[
            ],
            options={
                'verbose_name': 'NPC special item',
                'verbose_name_plural': 'NPC special items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('npcs.npcitem',),
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='npcitem',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='npcitem',
            name='snapshot_update',
        ),
        migrations.AddField(
            model_name='npcitem',
            name='special_xp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='npcitemevent',
            name='special_xp',
            field=models.IntegerField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='npcitem',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "npcs_npcitemevent" ("created_at", "id", "item_id", "npc_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "relationship", "special_xp") VALUES (NEW."created_at", NEW."id", NEW."item_id", NEW."npc_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."relationship", NEW."special_xp"); RETURN NULL;', hash='c97e714884c844819212e4be8f5cdbe9e484390f', operation='INSERT', pgid='pgtrigger_snapshot_insert_fa74a', table='npcs_npcitem', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='npcitem',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."npc_id" IS DISTINCT FROM (NEW."npc_id") OR OLD."item_id" IS DISTINCT FROM (NEW."item_id") OR OLD."relationship" IS DISTINCT FROM (NEW."relationship") OR OLD."special_xp" IS DISTINCT FROM (NEW."special_xp") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func='INSERT INTO "npcs_npcitemevent" ("created_at", "id", "item_id", "npc_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "relationship", "special_xp") VALUES (NEW."created_at", NEW."id", NEW."item_id", NEW."npc_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."relationship", NEW."special_xp"); RETURN NULL;', hash='87a4e90dc6cfa5b2825bca94c432df976562e4ff', operation='UPDATE', pgid='pgtrigger_snapshot_update_644af', table='npcs_npcitem', when='AFTER')),
        ),
    ]
