# Generated by Django 4.1.5 on 2023-03-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0002_no_m2m"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quest",
            name="required_silver",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="quest",
            name="reward_silver",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="questevent",
            name="required_silver",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="questevent",
            name="reward_silver",
            field=models.BigIntegerField(),
        ),
    ]
