# Generated by Django 4.2 on 2023-05-02 05:15

from django.db import migrations, models
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0004_quests_plural"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="quest",
            name="snapshot_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="quest",
            name="snapshot_update",
        ),
        migrations.AddField(
            model_name="quest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quest",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="questevent",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questevent",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="quest",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "quests_questevent" ("author", "created_at", "description", "end_date", "id", "main_quest", "modified_at", "npc", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pred_id", "required_cooking_level", "required_crafting_level", "required_exploring_level", "required_farming_level", "required_fishing_level", "required_npc_id", "required_npc_level", "required_silver", "required_tower_level", "reward_gold", "reward_silver", "start_date", "title") VALUES (NEW."author", NEW."created_at", NEW."description", NEW."end_date", NEW."id", NEW."main_quest", NEW."modified_at", NEW."npc", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."pred_id", NEW."required_cooking_level", NEW."required_crafting_level", NEW."required_exploring_level", NEW."required_farming_level", NEW."required_fishing_level", NEW."required_npc_id", NEW."required_npc_level", NEW."required_silver", NEW."required_tower_level", NEW."reward_gold", NEW."reward_silver", NEW."start_date", NEW."title"); RETURN NULL;',
                    hash="774e9d8cd7426168b505430adc1ec14963908b4b",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_d9ad1",
                    table="quests_quest",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="quest",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "quests_questevent" ("author", "created_at", "description", "end_date", "id", "main_quest", "modified_at", "npc", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pred_id", "required_cooking_level", "required_crafting_level", "required_exploring_level", "required_farming_level", "required_fishing_level", "required_npc_id", "required_npc_level", "required_silver", "required_tower_level", "reward_gold", "reward_silver", "start_date", "title") VALUES (NEW."author", NEW."created_at", NEW."description", NEW."end_date", NEW."id", NEW."main_quest", NEW."modified_at", NEW."npc", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."pred_id", NEW."required_cooking_level", NEW."required_crafting_level", NEW."required_exploring_level", NEW."required_farming_level", NEW."required_fishing_level", NEW."required_npc_id", NEW."required_npc_level", NEW."required_silver", NEW."required_tower_level", NEW."reward_gold", NEW."reward_silver", NEW."start_date", NEW."title"); RETURN NULL;',
                    hash="7602b01762151c89b02c9f5e1cd275b6e6c1f478",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_f7ef5",
                    table="quests_quest",
                    when="AFTER",
                ),
            ),
        ),
    ]
