# Generated by Django 4.2 on 2023-05-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0008_remove_quest_snapshot_insert_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quest",
            name="npc_img",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="questevent",
            name="npc_img",
            field=models.CharField(max_length=255),
        ),
    ]
