# Generated by Django 4.2.2 on 2023-06-12 21:50

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0012_clean_description"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="questitemrequired",
            name="snapshot_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="questitemrequired",
            name="snapshot_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="questitemreward",
            name="snapshot_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="questitemreward",
            name="snapshot_update",
        ),
        migrations.AddField(
            model_name="questitemrequired",
            name="order",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questitemrequiredevent",
            name="order",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questitemreward",
            name="order",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questitemrewardevent",
            name="order",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="questitemrequired",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "quests_questitemrequiredevent" ("id", "item_id", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quantity", "quest_id") VALUES (NEW."id", NEW."item_id", NEW."order", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."quantity", NEW."quest_id"); RETURN NULL;',
                    hash="f6146ebf1b5c41dd1871f0770e7b809f78c82681",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_33d3b",
                    table="quests_questitemrequired",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="questitemrequired",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "quests_questitemrequiredevent" ("id", "item_id", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quantity", "quest_id") VALUES (NEW."id", NEW."item_id", NEW."order", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."quantity", NEW."quest_id"); RETURN NULL;',
                    hash="a9a85838718ae41aa0778749767db63f1710dfc3",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_8962c",
                    table="quests_questitemrequired",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="questitemreward",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "quests_questitemrewardevent" ("id", "item_id", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quantity", "quest_id") VALUES (NEW."id", NEW."item_id", NEW."order", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."quantity", NEW."quest_id"); RETURN NULL;',
                    hash="f6961bee1bd0b5917428b7d71a7cdb9d308cce4a",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_272f4",
                    table="quests_questitemreward",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="questitemreward",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "quests_questitemrewardevent" ("id", "item_id", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quantity", "quest_id") VALUES (NEW."id", NEW."item_id", NEW."order", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."quantity", NEW."quest_id"); RETURN NULL;',
                    hash="e37bc9d970c4049b096361ef7339a296fd2d0869",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_b391c",
                    table="quests_questitemreward",
                    when="AFTER",
                ),
            ),
        ),
    ]
