# Generated by Django 4.2.2 on 2023-06-19 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("npcs", "0003_is_available"),
        ("quests", "0013_item_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quest",
            name="required_npc_id",
        ),
        migrations.RemoveField(
            model_name="questevent",
            name="required_npc_id",
        ),
        migrations.AddField(
            model_name="quest",
            name="required_npc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quests",
                to="npcs.npc",
            ),
        ),
        migrations.AddField(
            model_name="questevent",
            name="required_npc",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="npcs.npc",
            ),
        ),
    ]
