# Generated by Django 4.1.5 on 2023-04-10 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room", models.CharField(db_index=True, max_length=255)),
                ("ts", models.DateTimeField()),
                ("emblem", models.CharField(max_length=255)),
                ("username", models.CharField(db_index=True, max_length=255)),
                ("content", models.TextField()),
                ("flags", models.IntegerField(default=0)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_ts", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
