# Generated by Django 4.2 on 2023-05-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_emblem_emblemevent_emblem_snapshot_insert_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
