# Generated by Django 4.2 on 2023-05-21 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0012_manual_productions"),
        ("exchange_center", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="input_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exchange_center_inputs",
                to="items.item",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="output_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exchange_center_outputs",
                to="items.item",
            ),
        ),
    ]
