# Generated by Django 4.2 on 2023-05-25 05:45

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pghistory", "0005_events_middlewareevents"),
        ("items", "0013_cooking_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileBackground",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("light_image", models.CharField(max_length=255)),
                ("dark_image", models.CharField(max_length=255)),
                ("cost_silver", models.BigIntegerField(blank=True, null=True)),
                ("cost_gold", models.IntegerField(blank=True, null=True)),
                ("cost_item_quantity", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "cost_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_background_cost_items",
                        to="items.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfileBackgroundEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("game_id", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("light_image", models.CharField(max_length=255)),
                ("dark_image", models.CharField(max_length=255)),
                ("cost_silver", models.BigIntegerField(blank=True, null=True)),
                ("cost_gold", models.IntegerField(blank=True, null=True)),
                ("cost_item_quantity", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cost_item",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="items.item",
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="event",
                        to="pbgs.profilebackground",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profilebackground",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pbgs_profilebackgroundevent" ("cost_gold", "cost_item_id", "cost_item_quantity", "cost_silver", "created_at", "dark_image", "game_id", "id", "light_image", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."cost_gold", NEW."cost_item_id", NEW."cost_item_quantity", NEW."cost_silver", NEW."created_at", NEW."dark_image", NEW."game_id", NEW."id", NEW."light_image", NEW."name", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id"); RETURN NULL;',
                    hash="df9c520acd4fbf7c55287627b7e9491db99f1df0",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_fd18f",
                    table="pbgs_profilebackground",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profilebackground",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."game_id" IS DISTINCT FROM (NEW."game_id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."light_image" IS DISTINCT FROM (NEW."light_image") OR OLD."dark_image" IS DISTINCT FROM (NEW."dark_image") OR OLD."cost_silver" IS DISTINCT FROM (NEW."cost_silver") OR OLD."cost_gold" IS DISTINCT FROM (NEW."cost_gold") OR OLD."cost_item_id" IS DISTINCT FROM (NEW."cost_item_id") OR OLD."cost_item_quantity" IS DISTINCT FROM (NEW."cost_item_quantity") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at"))',
                    func='INSERT INTO "pbgs_profilebackgroundevent" ("cost_gold", "cost_item_id", "cost_item_quantity", "cost_silver", "created_at", "dark_image", "game_id", "id", "light_image", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."cost_gold", NEW."cost_item_id", NEW."cost_item_quantity", NEW."cost_silver", NEW."created_at", NEW."dark_image", NEW."game_id", NEW."id", NEW."light_image", NEW."name", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id"); RETURN NULL;',
                    hash="94d981db3f487a62322ac8a4afc4ee2573c0f9b2",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_fda59",
                    table="pbgs_profilebackground",
                    when="AFTER",
                ),
            ),
        ),
    ]
