# Generated by Django 4.1.5 on 2023-01-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="buy_price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
