# Generated by Django 4.1.5 on 2023-01-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_itemevent_item_snapshot_insert_item_snapshot_update_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="itemevent",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
