# Generated by Django 4.2 on 2023-05-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0008_locksmithitem_locksmithitemevent_recipeitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locksmithitem",
            name="quantity_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="locksmithitem",
            name="quantity_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="locksmithitemevent",
            name="quantity_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="locksmithitemevent",
            name="quantity_min",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
