# Generated by Django 4.2 on 2023-05-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0014_level_rewards"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skilllevelreward",
            options={"ordering": ["level", "order"]},
        ),
        migrations.AlterField(
            model_name="skilllevelreward",
            name="level",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="skilllevelreward",
            name="order",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="skilllevelreward",
            name="skill",
            field=models.CharField(
                choices=[
                    ("farming", "Farming"),
                    ("fishing", "Fishing"),
                    ("crafting", "Crafting"),
                    ("exploring", "Exploring"),
                    ("cooking", "Cooking"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="skilllevelreward",
            constraint=models.UniqueConstraint(
                fields=("skill", "level", "order"),
                name="skill_level_reward_level_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="skilllevelreward",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("gold", None),
                        ("item", None),
                        ("item_quantity", None),
                        ("silver__isnull", False),
                    ),
                    models.Q(
                        ("gold__isnull", False),
                        ("item", None),
                        ("item_quantity", None),
                        ("silver", None),
                    ),
                    models.Q(
                        ("gold", None),
                        ("item__isnull", False),
                        ("item_quantity__isnull", False),
                        ("silver", None),
                    ),
                    _connector="OR",
                ),
                name="skill_level_reward_only_one_type",
            ),
        ),
    ]
