# Generated by Django 4.2 on 2023-06-04 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0017_ak"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="cooking_recipe_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cooking_recipe_cookable",
                to="items.item",
            ),
        ),
    ]
