# Generated by Django 4.2 on 2023-05-25 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0009_alter_quest_npc_img_alter_questevent_npc_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Questline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("image", models.CharField(max_length=255)),
                ("automatic", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="QuestlineStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questlines",
                        to="quests.quest",
                    ),
                ),
                (
                    "questline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="quests.questline",
                    ),
                ),
            ],
            options={
                "ordering": ["questline", "order"],
            },
        ),
    ]
