# Generated by Django 4.2 on 2023-05-06 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0006_remove_item_snapshot_insert_and_more"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DropRates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iron_depot", models.BooleanField(blank=True, null=True)),
                ("runecube", models.BooleanField(blank=True, null=True)),
                ("manual_fishing", models.BooleanField(blank=True, null=True)),
                ("hash", models.BigIntegerField(blank=True, null=True)),
                ("compute_time", models.FloatField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drop_rates",
                        to="locations.location",
                    ),
                ),
                (
                    "seed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drop_rates",
                        to="items.item",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "drop rates",
            },
        ),
        migrations.CreateModel(
            name="DropRatesItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.FloatField()),
                (
                    "drop_rates",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="locations.droprates",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drop_rates_items",
                        to="items.item",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="droprates",
            constraint=models.UniqueConstraint(
                fields=("location", "seed", "iron_depot", "runecube", "manual_fishing"),
                name="location_flags",
            ),
        ),
        migrations.AddConstraint(
            model_name="droprates",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("location", None), ("seed__isnull", False)),
                    models.Q(("location__isnull", False), ("seed", None)),
                    _connector="OR",
                ),
                name="location_or_seed",
            ),
        ),
    ]
