# Generated by Django 4.2 on 2023-05-08 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_base_drop_rates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="droprates",
            options={
                "ordering": ["location", "seed", "runecube", "pk"],
                "verbose_name_plural": "drop rates",
            },
        ),
    ]
