# Generated by Django 4.2 on 2023-05-21 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("items", "0012_manual_productions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_quantity", models.IntegerField()),
                ("output_quantity", models.IntegerField()),
                ("oneshot", models.BooleanField()),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "input_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_center_input_items",
                        to="items.item",
                    ),
                ),
                (
                    "output_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_center_output_items",
                        to="items.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TradeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seen_at", models.DateTimeField()),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="exchange_center.trade",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="tradehistory",
            constraint=models.UniqueConstraint(
                fields=("trade", "seen_at"), name="trade_seen_at"
            ),
        ),
        migrations.AddConstraint(
            model_name="trade",
            constraint=models.UniqueConstraint(
                fields=(
                    "input_item",
                    "input_quantity",
                    "output_item",
                    "output_quantity",
                    "oneshot",
                ),
                name="items",
            ),
        ),
    ]
