# Generated by Django 4.2.2 on 2023-06-15 03:42

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pghistory", "0005_events_middlewareevents"),
        ("items", "0023_manual_href"),
        ("exchange_center", "0002_alter_trade_input_item_alter_trade_output_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardsTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spades_quantity", models.IntegerField(blank=True, null=True)),
                ("hearts_quantity", models.IntegerField(blank=True, null=True)),
                ("diamonds_quantity", models.IntegerField(blank=True, null=True)),
                ("clubs_quantity", models.IntegerField(blank=True, null=True)),
                ("joker_quantity", models.IntegerField(blank=True, null=True)),
                ("output_quantity", models.IntegerField()),
                ("is_disabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "output_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards_trades",
                        to="items.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CardsTradeEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("spades_quantity", models.IntegerField(blank=True, null=True)),
                ("hearts_quantity", models.IntegerField(blank=True, null=True)),
                ("diamonds_quantity", models.IntegerField(blank=True, null=True)),
                ("clubs_quantity", models.IntegerField(blank=True, null=True)),
                ("joker_quantity", models.IntegerField(blank=True, null=True)),
                ("output_quantity", models.IntegerField()),
                ("is_disabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "output_item",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="items.item",
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="event",
                        to="exchange_center.cardstrade",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="cardstrade",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "exchange_center_cardstradeevent" ("clubs_quantity", "created_at", "diamonds_quantity", "hearts_quantity", "id", "is_disabled", "joker_quantity", "output_item_id", "output_quantity", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "spades_quantity") VALUES (NEW."clubs_quantity", NEW."created_at", NEW."diamonds_quantity", NEW."hearts_quantity", NEW."id", NEW."is_disabled", NEW."joker_quantity", NEW."output_item_id", NEW."output_quantity", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."spades_quantity"); RETURN NULL;',
                    hash="070af7f69c40730dace2817943d4e4d6b6fd77c9",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_31283",
                    table="exchange_center_cardstrade",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="cardstrade",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."spades_quantity" IS DISTINCT FROM (NEW."spades_quantity") OR OLD."hearts_quantity" IS DISTINCT FROM (NEW."hearts_quantity") OR OLD."diamonds_quantity" IS DISTINCT FROM (NEW."diamonds_quantity") OR OLD."clubs_quantity" IS DISTINCT FROM (NEW."clubs_quantity") OR OLD."joker_quantity" IS DISTINCT FROM (NEW."joker_quantity") OR OLD."output_item_id" IS DISTINCT FROM (NEW."output_item_id") OR OLD."output_quantity" IS DISTINCT FROM (NEW."output_quantity") OR OLD."is_disabled" IS DISTINCT FROM (NEW."is_disabled") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at"))',
                    func='INSERT INTO "exchange_center_cardstradeevent" ("clubs_quantity", "created_at", "diamonds_quantity", "hearts_quantity", "id", "is_disabled", "joker_quantity", "output_item_id", "output_quantity", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "spades_quantity") VALUES (NEW."clubs_quantity", NEW."created_at", NEW."diamonds_quantity", NEW."hearts_quantity", NEW."id", NEW."is_disabled", NEW."joker_quantity", NEW."output_item_id", NEW."output_quantity", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."spades_quantity"); RETURN NULL;',
                    hash="1be09b5486d753a0ef2a633aa66ba4f65333de35",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_3c7c5",
                    table="exchange_center_cardstrade",
                    when="AFTER",
                ),
            ),
        ),
    ]
