# Generated by Django 4.2.2 on 2023-06-10 20:57

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ("npcs", "0002_remove_npc_snapshot_insert_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="npc",
            name="snapshot_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="npc",
            name="snapshot_update",
        ),
        migrations.AddField(
            model_name="npc",
            name="is_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="npcevent",
            name="is_available",
            field=models.BooleanField(default=False),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="npc",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "npcs_npcevent" ("created_at", "id", "image", "is_available", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "short_name") VALUES (NEW."created_at", NEW."id", NEW."image", NEW."is_available", NEW."name", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."short_name"); RETURN NULL;',
                    hash="51eb5e9cd329d7128cbdf426c3626d5b91bc68e6",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_d1bdb",
                    table="npcs_npc",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="npc",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."image" IS DISTINCT FROM (NEW."image") OR OLD."short_name" IS DISTINCT FROM (NEW."short_name") OR OLD."is_available" IS DISTINCT FROM (NEW."is_available") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at"))',
                    func='INSERT INTO "npcs_npcevent" ("created_at", "id", "image", "is_available", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "short_name") VALUES (NEW."created_at", NEW."id", NEW."image", NEW."is_available", NEW."name", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."short_name"); RETURN NULL;',
                    hash="b17decfebbbba8c4b9311a730db8c94a38158582",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_9156b",
                    table="npcs_npc",
                    when="AFTER",
                ),
            ),
        ),
    ]
